version: '3'
services:
  caching-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: "--port 3000 --origin http://dummyjson.com"
    volumes:
      - .:/app
    restart: unless-stopped
